# Generated by Django 4.2.30 on 2026-08-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Track',
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Songs', 'verbose_name_plural': 'Songs'},
        ),
    ]
